# ------------------------------------------------------------------------------------------------------
# Example bash_profile for local machine.
# The dev env VM can be configured by setting environment variables on local machine.
# This file contains all those variables
# ------------------------------------------------------------------------------------------------------

